<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class DistanceInformation
{

    static $swaggerTypes = array(
        'DistanceM' => 'float',
        'IsApproximate' => 'bool'

    );

    /**
     * The distance, in meters
     */
    public $DistanceM; // float
    /**
     * Whether the distance is an approximation (possibly &quot;as the crow flies&quot;), or a measured network distance
     */
    public $IsApproximate; // bool
}