<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Fare
{

    static $swaggerTypes = array(
        'MinimumZone' => 'int',
        'MaximumZone' => 'int',
        'TotalZones' => 'int',
        'Fares' => 'array[FareDetail]'

    );

    /**
     * The inner-most zone the fare covers
     */
    public $MinimumZone; // int
    /**
     * The outer-most zone the fare covers
     */
    public $MaximumZone; // int
    /**
     * The total number of unique zones the fare is travelling through
     */
    public $TotalZones; // int
    /**
     * The fare amount for each ticket type, eg go-card concession, go-card adult
     */
    public $Fares; // array[FareDetail]
}