<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Itinerary
{

    static $swaggerTypes = array(
        'Fare' => 'Fare',
        'Legs' => 'array[Leg]',
        'StartTime' => 'DateTime',
        'FirstDepartureTime' => 'DateTime',
        'EndTime' => 'DateTime',
        'LastArrivalTime' => 'DateTime',
        'DurationMins' => 'int',
        'Transfers' => 'int'

    );

    /**
     * Fares involved if this journey is taken, and the zones involved
     */
    public $Fare; // Fare
    /**
     * Individual legs/parts that make up this journey
     */
    public $Legs; // array[Leg]
    /**
     * When the customer's journey starts, including any walking time involved to reach the first public transport component
     */
    public $StartTime; // DateTime
    /**
     * When the first non-walking component of the journey departs its origin
     */
    public $FirstDepartureTime; // DateTime
    /**
     * When the customer would arrive at their destination, including any walking times involved
     */
    public $EndTime; // DateTime
    /**
     * When the last non-walking component of the journey arrives at its destination
     */
    public $LastArrivalTime; // DateTime
    /**
     * Total duration of the trip in minutes, including any walking components
     */
    public $DurationMins; // int
    /**
     * Total number of vehicle transfers the journey involves
     */
    public $Transfers; // int
}