<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class RoutesByLine
{

    static $swaggerTypes = array(
        'LineName' => 'string',
        'LineId' => 'string',
        'Routes' => 'array[RoutesByLineItem]',
        'VehicleType' => 'string'

    );

    /**
     * Display name of the Line, eg Doomben or CitiCat, or for Buses the actual Bus Route, eg 111
     */
    public $LineName; // string
    /**
     * Unique identifie of this Line
     */
    public $LineId; // string
    /**
     * Summary of route codes which travel on this line. Unique within a particular RoutesByLine.VehicleType
     */
    public $Routes; // array[RoutesByLineItem]
    /**
     * Type of Vehicle that travles on this Line. None = 0, Bus = 2, Ferry = 4, Train = 8, Walk = 16
     */
    public $VehicleType; // string
}