<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Stop
{

    static $swaggerTypes = array(
        'StopId' => 'string',
        'ServiceType' => 'string',
        'Zone' => 'string',
        'ParentLocation' => 'Location',
        'HasParentLocation' => 'bool',
        'Street' => 'string',
        'Suburb' => 'string',
        'Intersection1' => 'string',
        'Intersection2' => 'string',
        'StopNoteCodes' => 'string',
        'LocationDescription' => 'string',
        'Routes' => 'array[Route]',
        'Id' => 'string',
        'Description' => 'string',
        'Type' => 'string',
        'Position' => 'LatLng',
        'LandmarkType' => 'string'

    );

    /**
     * Unique Translink Stop ID of this stop
     */
    public $StopId; // string
    /**
     * Type of the stop, eg Bus. Bus = 1, Train = 2, Ferry = 3
     */
    public $ServiceType; // string
    /**
     * Translink travel Zone this stop is within. For stops on zone boundaries may be represented as zone1/zone2, eg 4/5
     */
    public $Zone; // string
    /**
     * The parent location this stop is a part of, if any. For example, busway platforms 'Roma Street Station Platform 1' is a unique stops and is modeled as a child of the parent location 'Roma Street Station'
     */
    public $ParentLocation; // Location
    /**
     * Whether the stop has a parent location
     */
    public $HasParentLocation; // bool
    /**
     * The street address of this stop
     */
    public $Street; // string
    /**
     * The stops suburb
     */
    public $Suburb; // string
    /**
     * Description of the street intersection
     */
    public $Intersection1; // string
    /**
     * Description of the street intersection
     */
    public $Intersection2; // string
    /**
     * Note codes unique to the stop
     */
    public $StopNoteCodes; // string
    /**
     * Textual description of the location
     */
    public $LocationDescription; // string
    /**
     * Routes which travel through this stop
     */
    public $Routes; // array[Route]
    /**
     *
     */
    public $Id; // string
    /**
     *
     */
    public $Description; // string
    /**
     * . None = 0, Landmark = 1, StreetAddress = 2, Stop = 3, GeographicPosition = 4
     */
    public $Type; // string
    /**
     *
     */
    public $Position; // LatLng
    /**
     *
     */
    public $LandmarkType; // string
}